
name:        flatparse
version:     0.3.0.1
license:     MIT
category:    Parsing
synopsis:    High-performance parsing from strict bytestrings
author:      Andr치s Kov치cs
maintainer:  puttamalac@gmail.com
copyright:   2021 Andr치s Kov치cs
bug-reports: https://github.com/AndrasKovacs/flatparse/issues
github:      AndrasKovacs/flatparse

description: |
  @Flatparse@ is a high-performance parsing library, focusing on programming languages and
  human-readable data formats. See the README for more information:
  <https://github.com/AndrasKovacs/flatparse>.

tested-with:
  - GHC == 8.6.5
  - GHC == 8.8.4
  - GHC == 8.10.7
  - GHC == 9.0.1

dependencies:
  - base >= 4.7 && < 5

extra-source-files:
  - README.md

default-extensions:
  - BangPatterns
  - BlockArguments
  - ExplicitNamespaces
  - LambdaCase
  - MagicHash
  - OverloadedStrings
  - PatternSynonyms
  - TemplateHaskell
  - TupleSections
  - CPP

ghc-options:
  - -Wall
  - -Wno-name-shadowing
  - -Wno-unused-binds
  - -Wno-unused-matches
  - -Wno-missing-signatures

library:
  source-dirs:
    - src
  dependencies:
    - containers
    - bytestring
    - template-haskell
    - integer-gmp
  ghc-options:
    - -O2
    - -fllvm
    # - -ddump-simpl
    # - -dsuppress-all
    # - -dno-suppress-type-signatures
    # - -ddump-to-file
    # - -ddump-stg
    # - -ddump-llvm

tests:
  spec:
    main: Test.hs
    source-dirs:
      - test
    dependencies:
      - bytestring
      - flatparse
      - HUnit
      - hspec
    default-extensions:
      - ExtendedDefaultRules
    ghc-options:
      - -O2
      - -fllvm
      - -Wno-type-defaults

benchmarks:
  bench:
    source-dirs: bench
    main: Bench.hs
    dependencies:
      - attoparsec
      - bytestring
      - flatparse
      - gauge
      - megaparsec
      - parsec
      - primitive
      - integer-gmp
    ghc-options:
      - -O2
      - -fllvm
