
name:        flatparse
version:     0.1.0.0
license:     MIT
category:    Parsing
description: "High-performance parsing from strict bytestrings"
author:      "Andr치s Kov치cs"
maintainer:  "puttamalac@gmail.com"
copyright:   "2021 Andr치s Kov치cs"

dependencies:
- base >= 4.7 && < 5

default-extensions:
  - BangPatterns
  - BlockArguments
  - ExplicitNamespaces
  - LambdaCase
  - MagicHash
  - OverloadedStrings
  - PatternSynonyms
  - TemplateHaskell
  - TupleSections
  - UnboxedTuples

ghc-options:
  - -Wall
  - -Wno-name-shadowing
  - -Wno-unused-binds
  - -Wno-unused-matches
  - -Wno-missing-signatures

library:
  source-dirs:
    - src
  dependencies:
    - containers
    - bytestring
    - template-haskell
  ghc-options:
    - -O2
    # - -ddump-simpl
    # - -dsuppress-all
    # - -dno-suppress-type-signatures
    # - -ddump-stg
    # - -ddump-to-file
    # - -ddump-asm
    # - -ddump-llvm

executables:
  test:
    source-dirs: test
    main: Test.hs

  bench:
    source-dirs: bench
    main: Bench.hs
    dependencies:
      - flatparse
      - bytestring
      - gauge
      - megaparsec
      - attoparsec
      - parsec
    ghc-options:
      - -fllvm
      - -O2
      # - -ddump-simpl
      # - -dsuppress-all
      # - -dno-suppress-type-signatures
      # - -ddump-stg
      # - -ddump-to-file
