resolver: lts-16.31

packages:
- .

ghc-options:
    "$everything": -split-sections

extra-deps:
- bytesmith-0.3.7.0
- byteslice-0.2.5.2
- contiguous-0.5.1
- run-st-0.1.1.0
- primitive-unlifted-0.1.3.0
- tuples-0.1.0.0
