name: CI
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cabal: ["3.4"]
        ghc: ["8.8.4", "8.10.4"]
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/cache@v2
        with:
          path: ${{ runner.temp }}/llvm
          key: llvm-7.1.0
      - uses: KyleMayes/install-llvm-action@v1
        with:
          version: "7.1.0"
          directory: ${{ runner.temp }}/llvm
          cached: ${{ steps.cache-llvm.outputs.cache-hit }}      
      - uses: haskell/actions/setup@v1.2
        id: setup-haskell-cabal
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}
      - run: cabal v2-update
      - run: cabal v2-freeze 
      - uses: actions/cache@v2.1.3
        with:
          path: |
            ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
            dist-newstyle
          key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.ghc }}-
      - run: cabal v2-build
      - run: cabal v2-haddock 
      - run: cabal v2-sdist
